name: Azure Cost Report
on:
  workflow_dispatch:
jobs:
  azure-costs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run Azure cost script
        shell: pwsh
        run: ./scripts/get-costs-azure.ps1