name: GCP Cost Report
on:
  workflow_dispatch:
jobs:
  gcp-costs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run GCP cost script
        shell: pwsh
        run: ./scripts/get-costs-gcp.ps1